name: example
description: "An example Flutter app demonstrating the simplest_calculator package."
publish_to: 'none' # Prevents accidental publication to pub.dev

# Versioning information
version: 1.0.0+1

# Define compatible Dart and Flutter versions
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

# Dependencies required for the example app
dependencies:
  flutter:
    sdk: flutter

  # Example package dependency (local reference to the parent package)
  simplest_calculator:
    path: ../

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
